name: Check Kubernetes YAMLs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scan repo
        id: kube-lint-repo
        uses: stackrox/kube-linter-action@v0.0.1
        with:
          directory: yamls
          config: .kube-linter/config.yaml

